### PR TITLE
Expose the filename as a public non-inlinable constant

### PR DESCRIPTION
**Pull request by stephenc**
- Needs to come via a static method in case we ever need to change it so that dependencies using it do not have to be recompiled

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
(this is a cloudbees maintained plugin) :+1:

**Pull request merged**
